export enum ModalEventKey {
    MAKE_PAYMENTS = 'MAKE_PAYMENTS',
    DASHBOARD_MENU = 'DASHBOARD_MENU',
    SAVE_MERCHANT_ACCOUNT = 'SAVE_MERCHANT_ACCOUNT',
    SUSPEND_OPERATOR_ACCOUNT = 'SUSPEND_OPERATOR_ACCOUNT',
    ACTIVE_OPERATOR_ACCOUNT = 'ACTIVE_OPERATOR_ACCOUNT',
    EDIT_MERCHANT_ACCOUNT = 'EDIT_MERCHANT_ACCOUNT',
    LOG_OUT = 'LOG_OUT'
}
